language: minimal

services:
  - docker

before_install:
- curl -J -L http://www.mediafire.com/file/awc7tbx78b7rxe7/entiredata_2019_04_19_11_56_am.zip/file --output cisbp.zip
- unzip cisbp.zip -d tasks/data/cisbp_rna
- rm cisbp.zip
- cp .env-template .env
- docker-compose -f docker-compose.yml -f docker-compose.test.yml build

script:
- docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit