language: minimal

services:
  - docker

before_install:
- curl -L $(curl http://cisbp-rna.ccbr.utoronto.ca/bulk_archive.php | grep href=\"tmp | grep -o 'tmp/.*\.zip' | awk '{print "http://cisbp-rna.ccbr.utoronto.ca/"$1}') --output cisbp.zip
- unzip cisbp.zip -d tasks/data/cisbp_rna
- rm cisbp.zip
- cp .env-template .env
- docker-compose -f docker-compose.yml -f docker-compose.test.yml build

script:
- docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit