language: minimal

services:
  - docker

before_install:
- wget -O cisbp.zip http://download2268.mediafire.com/fwe26vxh3lng/awc7tbx78b7rxe7/entiredata_2019_04_19_11_56_am.zip
- unzip cisbp.zip -d tasks/data/cisbp_rna
- rm cisbp.zip
- cp .env-template .env
- docker-compose -f docker-compose.yml -f docker-compose.test.yml build

script:
- docker-compose -f docker-compose.yml -f docker-compose.test.yml up --abort-on-container-exit