version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
            - "5555:5555"
            - "9001:9001"
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: redis
        ports:
            - "9736:6379"