version: '3'
services:
    web:
        container_name: cneat_web
        environment:
            - DEBUG=${DEBUG}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        build:
            context: .
            dockerfile: Dockerfile-web
        ports:
            - "6565:5000"
        volumes:
            - .:/app
        depends_on:
            - redis
            - celery
    celery:
        container_name: cneat_celery
        environment:
            - FLOWER_USER=${FLOWER_USER}
            - FLOWER_PASSWORD=${FLOWER_PASSWORD}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        build:
            context: .
            dockerfile: Dockerfile-celery
        ports:
            - "5555:5555"
            - "9001:9001"
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        container_name: cneat_redis
        image: redis
        ports:
            - "9736:6379"
        volumes:
            - ./data:/data
        entrypoint: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
        restart: always