version: '3'
services:
    pytest:
        container_name: cneat_test_pytest
        build:
            context: .
            dockerfile: Dockerfile-pytest
        volumes:
            - ./tests:/tests
        depends_on:
            - web
            - redis
    web:
        container_name: cneat_test_web
        environment:
            - DEBUG=1
    celery:
        container_name: cneat_test_celery
        logging:
            driver: "none"
    redis:
        container_name: cneat_test_redis
        entrypoint: redis-server --requirepass ${REDIS_PASSWORD} --appendonly no
        logging:
            driver: "none"