version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile-web
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        depends_on:
            - redis
            - celery
    celery:
        build:
            context: .
            dockerfile: Dockerfile-celery
        ports:
            - "5555:5555"
            - "9001:9001"
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: redis
        ports:
            - "9736:6379"
        volumes:
            - ./data:/data
        entrypoint: redis-server --appendonly yes
        restart: always