version: '3'
services:
    web:
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        build:
            context: .
            dockerfile: Dockerfile-web
        volumes:
            - .:/app
        depends_on:
            - redis
            - celery
    celery:
        environment:
            - FLOWER_USER=${FLOWER_USER}
            - FLOWER_PASSWORD=${FLOWER_PASSWORD}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        build:
            context: .
            dockerfile: Dockerfile-celery
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: redis
        entrypoint: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes