version: '3'
services:
    web:
        container_name: cneat_local_web
        environment:
            - DEBUG=1
        ports:
            - "6565:5000"
    celery:
        container_name: cneat_local_celery
        environment:
            - DEBUG=1
        ports:
            - "5555:5555"
    redis:
        container_name: cneat_local_redis
        ports:
            - "6379:6379"
        volumes:
            - ./data:/data
        restart: always